### ISSUE TITLE
web2exe

### ISSUE THREAD

**Issue by Hunlongyu** [shuax/shuax.com#1]
https://shuax.com/#Web2Exe

哈喽大佬， web2exe 有计划开源么？或者能让我鉴赏一下源码么？最近用 qt 开发，虽然比 electron 小很多，但是依旧很大。

很早就用大佬的 MouseInc 这款软件，看到只有几百KB，惊掉下巴，虽然我用 rust 压缩编译的二进制也可以很小，但明显界面没有用前端技术开发的好看。开发效率上也是没得比。

后来在官网看到 web2exe ，看了一下结构，很简洁。很nice。

是不是 dist 压缩的不是 zip 格式，我解压后，再反手压缩成 zip。就 404 了。更别提，我自己写了很多 demo 压缩 zip 文件包，打开时都是 404.

同时由于看不到源码，也不清楚运行原理，如：index.html 是通过本地文件的形式访问的（file:///.../index.html），还是启动微服务器，通过 http 的方式访问？

其他的，如：
是否支持远程地址访问？
是否支持远程更新？
是否支持跨域访问？
能否支持动态库 dll 调用？
是否支持开机自启？
能否支持注册表修改等等。。。

望大佬解惑，祝安康~

**Comment by shuax** [comment]
就是对webview2的简单调用，没有开源打算。你重新打包的zip不行可能是选择的压缩算法问题吧。后面那些功能都没打算加。

**Comment by shuax** [comment]
你会rust可以选 https://github.com/tauri-apps/tauri 吧。

**Comment by Hunlongyu** [comment]
tauri 接触过，开发过几个 demo。

但我最近从前端 转 C++ 了，之前学习是 rust 是兴趣。但是转 C++ 是我后面的职业规划。
短期内因为要学习很多C++ 知识，就不考虑 rust 了。

谢回复~😊
